name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    env:
      # make un-frozen strings fail so we see where we'd be sending warnings in ruby 3.4+
      RUBYOPT: "--enable-frozen-string-literal"
    runs-on: ubuntu-latest
    # keep ruby versions in sync with premailer.gemspec and .rubocop.yml
    strategy:
      matrix:
        task: ["test"]
        ruby: [ '3.0', '3.1', '3.2', '3.3' ]
        include:
          - task: rubocop
            ruby: '3.0' # lowest supported version
    name: ${{ matrix.ruby }} rake ${{ matrix.task }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rake ${{ matrix.task }}
